# JOIN lv3
# https://school.programmers.co.kr/learn/courses/30/lessons/59042

# LEFT JOIN
SELECT A_OUTS.ANIMAL_ID, A_OUTS.NAME
FROM ANIMAL_OUTS AS A_OUTS
LEFT JOIN ANIMAL_INS AS A_INS
ON A_OUTS.ANIMAL_ID = A_INS.ANIMAL_ID
WHERE A_INS.ANIMAL_ID is null;

# NOT IN
SELECT A_OUTS.ANIMAL_ID, A_OUTS.NAME
FROM ANIMAL_OUTS AS A_OUTS
WHERE A_OUTS.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS);
